### ISSUE TITLE
proportions_calculation() function - add 'process' option

### ISSUE THREAD

**Issue by gemmanewbold** [l-gorman/rhomis-R-package#37]
Hi Leo,
Could the proportions_calculation() function be adapted so that the ‘use’ options also include ‘process’ as well as ‘eat’, ‘sell’, and ‘feed_livestock’? I think this might be necessary to be able to use this function on the processed (process_eaten and process_sold) columns of our Tree Aid RHoMIS data, as ‘process’ is one of the options in our ‘use_column’s.
Cheers,
Gemma, Tree Aid

**Comment by l-gorman** [comment]
Thanks for the comment Gemma! 

I will try and do this, one thing to note however is this will only work in the case where you have a "use" column and a "prop" column. The "use" column contains information on the uses of the produce (e.g. `c("eat sell", "eat", "feed_livestock"...)`). Then for the use you are interested in there will need to be a corresponding "prop" column, (e.g. a column for fp_feed_livestock which would look like `fp_feed_livestock=c("all", NA, "half"...)`).

I will add the ability to check for these extra uses, but will need to add a check to see if the corresponding "use" column exists. Does that make sense?

**Comment by l-gorman** [comment]
Added the fix, (see the above commit). I am making other changes at the moment too, so this fix will be deployed once I have merged [this PR](https://github.com/l-gorman/rhomis-R-package/pull/36)
